version: '3.5'

services:

  ##### APPLICATIONS #####

  api:
    container_name: server
    image: node:10.16.0-alpine
    volumes:
      - .:/src
    environment:
      - APP_ENV=local
      - APP_HOST=http://localhost:8000
      - APP_PORT=3000
      - TZ=Asia/Bangkok
      # - MARIADB_MASTER=mariadb
      # - MARIADB_SLAVES=mariadb,mariadb
      # - MARIADB_USERNAME=root
      # - MARIADB_PASSWORD=admin
      # - MARIADB_PORT=3306
      # - MONGODB_URI=mongodb:27017
      # - MONGODB_USERNAME=root
      # - MONGODB_PASSWORD=admin
      - CORS_ORIGINS=http://localhost:3000
      - JWT_KEY=1234
    networks:
      - backend
    ports:
      - 3000:3000
    # depends_on:
    #   - mongodb
    #   - mariadb
    #   - redis-cluster
    working_dir: /src/app/api
    command: yarn dev

  ##### DATA STORES #####

  # mariadb:
  #   container_name: mariadb
  #   image: mariadb:10.3
  #   networks:
  #     - backend
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=admin
  #     - TZ=Asia/Bangkok
  #     - MYSQL_DATABASE=graphql-server
  #     - MYSQL_USER=admin
  #     - MYSQL_PASSWORD=admin
  #   volumes:
  #     - ./data/mariadb:/var/lib/mysql
  #   ports:
  #     - 3306:3306

  # mongodb:
  #   container_name: mongodb
  #   image: mongo:3.4
  #   networks:
  #     - backend
  #   environment:
  #     - MONGO_INITDB_ROOT_USERNAME=root
  #     - MONGO_INITDB_ROOT_PASSWORD=admin
  #     - TZ=Asia/Bangkok
  #   volumes:
  #     - ./data/mongodb:/data/db
  #   ports:
  #     - 27017:27017

  # redis-cluster:
  #   container_name: redis-cluster
  #   image: grokzen/redis-cluster:5.0.4
  #   networks:
  #     - backend
  #   ports:
  #     - 7000-7007:7000-7007
  #     - 5000-5002:5000-5002

  # ##### DATA STORES MANAGEMENT #####

  # phpmyadmin:
  #   container_name: phpmyadmin
  #   image: phpmyadmin/phpmyadmin
  #   networks:
  #     - backend
  #   ports:
  #     - 8080:80
  #   environment:
  #     - PMA_HOST=mariadb
  #     - PMA_USER=root
  #     - PMA_PASSWORD=admin
  #     - TZ=Asia/Bangkok
  #   depends_on:
  #     - mariadb

  # mongo-express:
  #   container_name: mongo-express
  #   image: mongo-express:0.49
  #   networks:
  #     - backend
  #   ports:
  #     - 8081:8081
  #   depends_on:
  #     - mongodb
  #   environment:
  #     - ME_CONFIG_MONGODB_SERVER=mongodb
  #     - ME_CONFIG_SITE_BASEURL=/
  #     - ME_CONFIG_MONGODB_ADMINUSERNAME=root
  #     - ME_CONFIG_MONGODB_ADMINPASSWORD=admin
  #     - TZ=Asia/Bangkok
  #   restart: always

  ##### AWS SERVICES #####

  # localstack:
  #   container_name: localstack
  #   image: localstack/localstack:latest
  #   networks:
  #     - backend
  #   ports:
  #     - 4567-4586:4567-4586
  #     - 4592:4592
  #     - 8085:8080
  #   environment:
  #     - SERVICES=s3,lambda,sqs,ses,apigateway,es,cloudwatch,cloudformation,iam,sts
  #     - DEBUG=1
  #     - DEFAULT_REGION=ap-southeast-1
  #     - LAMBDA_EXECUTOR=docker
  #     - LAMBDA_DOCKER_NETWORK=gmmlive_backend
  #     - DATA_DIR=/tmp/localstack/data
  #     - DOCKER_HOST=unix:///var/run/docker.sock
  #   volumes:
  #     - ./data/localstack:/tmp/localstack
  #     - /var/run/docker.sock:/var/run/docker.sock

networks:
  backend:
